### PR TITLE
Fix package and other warnings/errors

### LINKED ISSUE #133: Fix warning about multiple `@polkadot/util` versions
```
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or deupe using your package manager.
The following conflicting packages were found:
	6.11.1	<unknown>
	5.9.2 	<unknown>
```

### PR DESCRIPTION
**Pull request by aidan-starke**
Closes #133

### CODE REVIEW

**Comment by aidan-starke** [comment]
@polkadot packages are a part of @cennznet/api.. there is one remaining warning:

`The following conflicting packages were found:
	5.9.2	<unknown>
	5.9.2	<unknown>`

Which I'm not sure how to deal with

**Comment by ken-centrality** [comment]
👀  looking now @aidan-starke

**Comment by ken-centrality** [comment]
@aidan-starke this change e6e22c8 will remove the ability to link the asset to IPFS when in single page view. I'd suggest introduce a new prop `linkToIPFS` with default as `false` to the `NFTRenderer` and set that prop to `true` for the single view, which is in `[serialNumber].tsx:536`.

Re `5.9.2 <unknown> 5.9.2 <unknown>` warning, nuking the `node_modules` seems to do the trick so all good there.

Everything else LGTM! 👍

**Comment by aidan-starke** [comment]
@ken-centrality on single page view there is a link below the image 'View on IPFS' which is a litho.mypinata.cloud/ipfs link and I found that to load faster than the ipfs.io link

**Comment by ken-centrality** [comment]
oh true, in that case can we simply wrap the the `a` tag around `<NFT...` component that link to the same one as `View on IPFS`, no need to create any additional props then!?

**Review by ken-centrality — APPROVED** [review]

**Pull request merged**
